### ISSUE TITLE
Where is the addon code?

### ISSUE THREAD

**Issue by workmanw** [ember-data/ember-data-filter#4]
This appears to be mostly just a shell of an ember-addon and an env config for `ENABLE_DS_FILTER`. Is the idea that the addon will be implemented here before 2.0 ships? Or am I overlooking something else?

**Comment by orf** [comment]
I'm also confused about this, what exactly is happening?

**Comment by pangratz** [comment]
> Is the idea that the addon will be implemented here before 2.0 ships?

I think the transition from 1.13 to 2.0 of Ember-Data hasn't left too much time to cleanly extract the `ember-data-filter` addon, that's why the code for the filter is still in the [`store.js`](https://github.com/emberjs/data/blob/1192a6c3e275b5446226971896d773297ddd87e2/packages/ember-data/lib/system/store.js#L1173-L1203)...

**Comment by pangratz** [comment]
I took another look at this and the code for `filter` is still located in `emberjs/data` repository, in [`store.js`](https://git.io/vzS2A). The filter can only be used though if `ENABLE_DS_FILTER` flag is set to `true`, see [this assertion](https://git.io/vzSat).

The only thing this addon does is enable this feature in [`config/environment.js`](https://git.io/vzSas).

**Comment by pangratz** [comment]
I am going to close this as I think it has been cleared where the code is. If you disagree, feel free to reopen.

**Comment by workmanw** [comment]
Yes it is. Thank you.
