### ISSUE TITLE
Using store.filter with params doesn't return the server results to the filter function

### ISSUE THREAD

**Issue by coferc** [ember-data/ember-data-filter#5]
Hi, I'm not sure if this is an issue or my misunderstanding of how store.filter should work when passing query params to it, but I thought this might be a good place to inquire.

The Ember guides say, "Optionally you can pass a query, which is the equivalent of calling find with that same query, to fetch additional records from the server...The query itself is not used to filter records, it's only sent to your server for you to be able to do server-side filtering. The filter function will be applied on the **returned results** regardless." (http://emberjs.com/api/data/classes/DS.Store.html#method_filter)

But I don't get just the server-returned results inside my filter function, I get the entire store for that model type. 

I'm using store.filter so I get a live array (whereas store.query doesn't return a live array), but I end up having to do redundant client-side filtering that mimics my server-side filtering in order to return the same result set that the server returned. This doesn't seem to match what the Ember guides say.

Example:
return this.store.filter('task', **params**, function(task) {  <<== server-side query
     // I get the entire store for this model, not just the server-side returned results, so I end up having to write filter conditions that simulate the query param values
});

Thank you!

**Comment by pangratz** [comment]
Hey, sorry for the late reply.

So the way the `filter` basically works is that the function gets invoked for every record of the passed type currently in the store. The function is invoked again, when:
- a record changes (so the affiliation into the result set is checked again).
- a new record is created
- a (new) record is pushed to the store

If you supply a `query`, an additional `store.query(...)` is trigged - not more, not less. This gives you a chance to ask the server for records which might not be in the store yet but which are relevant for the filter.

> I end up having to do redundant client-side filtering that mimics my server-side filtering in order to return the same result set that the server returned.

That's unfortunately currently the only way, since there is no mapping of a remote query and a local query :disappointed: .

---

> This doesn't seem to match what the Ember guides say.

The docs for `DS.Store#filter` might have been updated in the meantime to clarify this issue. Can you check if this is described better now?

**Comment by coferc** [comment]
Thanks, your clarification and confirmation that my method is ok is really helpful. The docs are the same, and could benefit from your extra explanation here I think. Thanks again
